const recipeSet = [
  [
    "Wheat Rava Halwa",
    "Jodhpuri Aloo",
    "Dairy Free Chocolate Pudding",
    "Thengai Sadam (A Quick and Healthy Coconut Rice)",
    "Baby Corn and Green Peas Sabzi",
    "Watermelon Carrot Radish Juice",
    "Moong Matar Kebab  - Green Lentil And Peas Kebab",
    "Bengali radish potato vegetable",
    "Besan Arbi Roast  - Spicy Colocasia Stir Fry",
    "Banana Pomegranate Raita  - Kela Anar Raita",
  ],
  [
    "Sesame Bread Patties  (Bread Cutlets)",
    "Nei Appam / Unniyappam  - Coconut Banana Fritters",
    "Tomato Jam",
    "Pasta In Tomato Onion Chutney",
    "Chunky Cucumber Salsa",
    "Soya Chunks Masala in Coconut Milk",
    "Orange Peppermint Green Tea Punch",
    "Kashmiri Phool Rogan Josh  - Cauliflower in Red Curry",
    "Bengali Style Kucho Nimki  (Diamond Shaped Salty Snacks)",
    "Enduri Pitha With Mango Twist",
  ],
  [
    "Rajasthani Style Oliya  (Sweetened Rice Yogurt Pudding )",
    "Gujarati Methi Na Dhebra",
    "Andhra Style Palakura Vepudu  - Spinach Stir Fry",
    "Andhra Style Chicken Fry",
    "Chilli Baby Corn (Manchurian)",
    "Palak Pakora",
    "Vatana Bateta Na Rotla  - Gujarati Peas and Potato Roti",
    "Mughlai Keema Paratha",
    "Pain Viennois | Vienna Bread",
    "Eggless Devil's Food Cake",
  ],
  [
    "Pacha Payir Kulambu  (South Indian Style Green Gram Curry)",
    "Matar Besan and Paneer Cheela  - Matar Besan and Paneer Cheela",
    "Ice Wine Panna Cotta",
    "Mushroom and Broccoli Soup  - Mushroom and Broccoli Soup",
    "Fruit Pachadi",
    "Assamese Saaru Maas Diya Adar Jhol  - Fish In Ginger Gravy",
    "Maa Ki Dal ()",
    "Breakfast Bar  With Berries Quinoa & Oats",
    "Punjabi Kadhi Pakora  - Delicious Punjabi Kadhi",
    "Rajasthani Ghasela  (Besan Ka Pitta)",
  ],
  [
    "Carrot Cake Parfait With Custard And Strawberries",
    "Mushroom Biryani",
    "Singapore Style Chicken Layered Fried Rice",
    "Stuffed Radish Paneer Paratha",
    "Dairy Free Chocolate Pudding",
    "Tomato Noodle Soup",
    "Ice Wine Panna Cotta",
    "Pudina Mavinakayi Chutney  - Mint Mango Chutney",
    "Dried Neem Flower Flavored Rice",
    "Kasuri methi leaves",
  ],
  [
    "Khara Obbattu  (Bread Stuffed With Spicy Potato Mixture )",
    "Jerk Chicken With Rice And Peas Pilaf",
    "Lugai Gosht  - Mutton In Spicy Tomato Onion Gravy",
    "Churros  With Cinnamon & Sugar | Eggless",
    "Shikampuri Kebab  - Kebabs made with Brown Chickpeas",
    "Poondu Milagu Kuzhambu  - Tamilnadu Style Garlic and Black Pepper Curry",
    "Kothamalli Thovayal  (Dry Coriander Leaves Chutney)",
    "Cucumber Neer Dosa -Rice Pancake",
    "Bamboo Shoot Stir Fry",
    "Matki Chi Rassa Bhaji  (Maharashtrian Style Moth Beans Cooked with Goda Masala)",
  ],
  [
    "Navrang dal  - Navrang Dal ()",
    "Mangalorean Style Bafat Pito -Bafat/Bafad Spice Mix Powder",
    "Breakfast Bar  With Berries Quinoa & Oats",
    "Smoked Dhaba Dal",
    "Bavarian Mushroom Sauce",
    "Besan Oats Ladoo",
    "Dahi Achari Bhindi  - Dahi Achari Bhindi",
    "Tomato Basil Chicken",
    "Roasted Peppers And Mushroom Tortilla Pizza",
    "French Toast BLT Bagel Sandwich",
  ],
  [
    "Spicy Lemon Chicken Kebab",
    "Posto Chicken  - Bengali Chicken In Poppy Seed Paste",
    "Breakfast Enchiladas With Mushroom Sauce",
    "Aloo Matar Masala Khichdi",
    "Pepper Mushroom Stir Fry",
    "Chak-Hao Amubi  (Black Rice Pudding)",
    "Eggplant Steaks",
    "Masala Cornflakes Chicken",
    "Thulli  (Broken Wheat Halwa)",
    "Prawn Masala Rice",
  ],
  [
    "Mukhadi Halwa  (Semolina & All Purpose Flour Halwa)",
    "Aloo Gajar Matar Sabzi",
    "Chow Chow Curry  - Chow Chow Curry",
    "Spicy Haryana Style Egg Curry",
    "Avocado Mint Soup  - Avocado Mint Soup",
    "Mullangi Mor Pachadi  (Radish in spicy tempered Yogurt Gravy )",
    "Wheat Phulka Yeast- Diabetic Friendly Baker's Yeast",
    "Kerala Special Mambazha Puliserry",
    "Pacha Manga Pachadi  - Raw Mango Pachadi",
    "Stuffed Omelette  With Cheesy Garlic Mushroom & Corn",
  ],
  [
    "Gujarati Kadhi With Milk And Mint",
    "Chanar Dal  - Bengali Steel Paneer & Potato Gravy",
    "Aloo Matar Masala Khichdi",
    "Kerala Style Chemmeen Moilee  - Prawn Curry",
    "Foxtail Millet Paruppu Adai With Keerai  - Foxtail Millet and Lentil Crepes with Spinach",
    "Moolangi Tovve  - Moolangi Tavve",
    "Andhra Style Multi Lentil Garelu (Vada )",
    "And fish soup  - Bengali fish curry",
    "Mini Dal Samosa Curry / Sabzi",
    "Mughlai Keema Paratha",
  ],
];

export default recipeSet;
